const BOOK_NAME_TO_OSIS: Record<string, string> = {
  'Genèse': 'Gen',
  'Exode': 'Exod',
  'Lévitique': 'Lev',
  'Nombres': 'Num',
  'Deutéronome': 'Deut',
  'Josué': 'Josh',
  'Juges': 'Judg',
  'Ruth': 'Ruth',
  '1 Samuel': '1Sam',
  '2 Samuel': '2Sam',
  '1 Rois': '1Kgs',
  '2 Rois': '2Kgs',
  '1 Chroniques': '1Chr',
  '2 Chroniques': '2Chr',
  'Esdras': 'Ezra',
  'Néhémie': 'Neh',
  'Tobie': 'Tob',
  'Judith': 'Jdt',
  'Esther': 'Esth',
  '1 Maccabées': '1Macc',
  '2 Maccabées': '2Macc',
  'Job': 'Job',
  'Psaumes': 'Ps',
  'Proverbes': 'Prov',
  'Ecclésiaste': 'Eccl',
  'Cantique des Cantiques': 'Song',
  'Sagesse de Salomon': 'Wis',
  'Siracide': 'Sir',
  'Isaïe': 'Isa',
  'Jérémie': 'Jer',
  'Lamentations': 'Lam',
  'Baruch': 'Bar',
  'Ézéchiel': 'Ezek',
  'Daniel': 'Dan',
  'Osée': 'Hos',
  'Joël': 'Joel',
  'Amos': 'Amos',
  'Abdias': 'Obad',
  'Jonas': 'Jonah',
  'Michée': 'Mic',
  'Nahum': 'Nah',
  'Habaquc': 'Hab',
  'Sophonie': 'Zeph',
  'Aggée': 'Hag',
  'Zacharie': 'Zech',
  'Malachie': 'Mal',
  'Matthieu': 'Matt',
  'Marc': 'Mark',
  'Luc': 'Luke',
  'Jean': 'John',
  'Actes des Apôtres': 'Acts',
  'Romains': 'Rom',
  '1 Corinthiens': '1Cor',
  '2 Corinthiens': '2Cor',
  'Galates': 'Gal',
  'Éphésiens': 'Eph',
  'Philippiens': 'Phil',
  'Colossiens': 'Col',
  '1 Thessaloniciens': '1Thess',
  '2 Thessaloniciens': '2Thess',
  '1 Timothée': '1Tim',
  '2 Timothée': '2Tim',
  'Tite': 'Titus',
  'Philémon': 'Phlm',
  'Hébreux': 'Heb',
  'Jacques': 'Jas',
  '1 Pierre': '1Pet',
  '2 Pierre': '2Pet',
  '1 Jean': '1John',
  '2 Jean': '2John',
  '3 Jean': '3John',
  'Jude': 'Jude',
  'Apocalypse': 'Rev'
};

export function getOsisRef(bookName: string, chapter?: number, verse?: number): string {
  const osisBook = BOOK_NAME_TO_OSIS[bookName] || bookName;
  if (chapter === undefined) return osisBook;
  if (verse === undefined) return `${osisBook}.${chapter}`;
  return `${osisBook}.${chapter}.${verse}`;
}
